### PR TITLE
Fix typos and translate docs to english

### PR DESCRIPTION
**Pull request by CholexMax**
Fixed typos of README for proper naming.
Translated some parts of the documentation to english so documentation can work perfectly for all users

### CODE REVIEW

**Comment by DaveSimoes** [comment]
Hi @CholexMax ...
Great job.

Thanks

**Comment by DaveSimoes** [comment]
Hi CholexMax !!

Great job !!

**Comment by DaveSimoes** [comment]
@CholexMax feel free to keep this translation if necessary

**Comment by CholexMax** [comment]
Thanks now I currently focus on to improve examples or new updates and concepts

**Pull request merged**
